--仿UI参考任务卡布局
SorrowClover=
{
  LinearLayout;--线性布局
  Orientation='vertical';--布局方向
  layout_width='fill';--布局宽度
  layout_height='fill';--布局高度
  background='#ff03a9f4';--布局背景颜色(或图片路径)
  {
    Toolbar;
    Title="任务";
    TitleTextColor="#ffffff";
  };
  {
    GridView;--网格控件
    id="grid";
    layout_width='fill';--网格宽度
    layout_height='fill';--网格高度
    Gravity='center';--对齐方式
    NumColumns='2';--列数
    --ColumnWidth='';--每一列的宽度
    --StretchMode='';--缩放
    HorizontalSpacing='16';--两列直接的边距
    VerticalSpacing='16';--两行之间的间距
    VerticalScrollBarEnabled=false;--隐藏竖向滑条
  };
};
activity.setContentView(loadlayout(SorrowClover))

item={
  LinearLayout;--线性布局
  Orientation='vertical';--布局方向
  layout_width='fill';--布局宽度
  layout_height='250dp';--布局高度
  gravity="center";
  {
    CardView;--卡片控件
    layout_margin='16';--卡片边距
    CardElevation='2';--卡片阴影
    layout_width='fill';--卡片宽度
    layout_height='fill';--卡片高度
    radius='16';--卡片圆角
    CardBackgroundColor='#ffffff';--卡片背景颜色
    {
      LinearLayout;--线性布局
      Orientation='vertical';--布局方向
      layout_width='fill';--布局宽度
      layout_height='fill';--布局高度
      Gravity="center";
      {
        CardView;--卡片控件
        id="card";
        CardElevation='0';--卡片阴影
        layout_width='50dp';--卡片宽度
        layout_height='50dp';--卡片高度
        radius='25dp';--卡片圆角
        CardBackgroundColor='#ffff1744';--卡片背景颜色
        alpha="0.5";
      };
      {
        TextView;--文本控件
        id="text";
        padding='16';--布局内边距
        layout_width='wrap';--文本宽度
        layout_height='wrap';--文本高度
        textColor='#000000';--文本颜色
        text='学习';--显示的文本
        textSize='20sp';--文本大小
      };
    };
  };
};
--创建项目数组
data={}
color_table={0xffff1744,0xff651fff,0xff00b0ff,0xff00e5ff,0xff00e676,0xffffea00,0xffffc400,0xffff3d00}
text_table={"学习","工作","健身","购物","唱歌","电影","料理","待开发"}
--创建适配器
adp=LuaAdapter(activity,data,item)
--添加数据
for n=1,8 do
  table.insert(data,{
    card={
      CardBackgroundColor=color_table[n],
    },
  text={
    Text=text_table[n]
    },
  })
end
--设置适配器
grid.Adapter=adp

grid.onItemClick=function(l,v,p,i)
  print(text_table[i])
  return true
end