SorrowClover=
{
  LinearLayout;--线性布局
  Orientation='vertical';--布局方向
  layout_width='fill';--布局宽度
  layout_height='fill';--布局高度
  background='#000000';--布局背景颜色(或图片路径)
  {
    LinearLayout;--线性布局
    Orientation='horizontal';--布局方向
    layout_width='fill';--布局宽度
    layout_height='200dp';--布局高度
    {
      CardView;--卡片控件
      layout_marginLeft='10%w';--卡片边距
      layout_gravity='left|center';--子控件在父布局中的对齐方式
      CardElevation='3';--卡片阴影
      layout_width='30%w';--卡片宽度
      layout_height='130dp';--卡片高度
      radius='20';--卡片圆角
      CardBackgroundColor='#EE7785';--卡片背景颜色
      {
        ImageView;--图片控件
        src='drawable/usertxs.png';--图片路径
        layout_width='fill';--图片宽度
        layout_height='fill';--图片高度
        layout_gravity='center';--对齐方式
        scaleType='fitXY';--图片缩放类型
      };
    };
    {
      LinearLayout;--线性布局
      layout_marginLeft='5%w',
      Orientation='vertical';--布局方向
      layout_width='fill';--布局宽度
      layout_height='fill';--布局高度
      gravity='left|center',
      {
        TextView;--文本控件
        layout_width='wrap';--文本宽度
        layout_height='wrap';--文本高度
        textColor='#ffffff';--文本颜色
        text='小何你吃嘛';--显示的文本
        textSize='20sp';--文本大小
      };
      {
        TextView;--文本控件
        layout_marginTop="5%w",
        layout_width='wrap';--文本宽度
        layout_height='wrap';--文本高度
        textColor='#ffffff';--文本颜色
        text='一个超级懒的人';--显示的文本
        textSize='12sp';--文本大小
      };
    };
  };
  {
    FrameLayout;--帧布局
    layout_width='fill';--布局宽度
    layout_height='fill';--布局高度
    {
      LinearLayout;--线性布局
      Orientation='vertical';--布局方向
      layout_width='fill';--布局宽度
      layout_height='fill';--布局高度
      {
        CardView;--卡片控件
        layout_width='fill';--卡片宽度
        layout_height='fill';--卡片高度
        radius='100';--卡片圆角
        CardBackgroundColor='#6AAFE6';--卡片背景颜色
        {
          LinearLayout;--线性布局
          Orientation='vertical';--布局方向
          layout_width='fill';--布局宽度
          layout_height='fill';--布局高度
          {
            LinearLayout;--线性布局
            Orientation='vertical';--布局方向
            layout_width='fill';--布局宽度
            layout_height='100dp';--布局高度
            {
              TextView;--文本控件
              layout_width='fill';--文本宽度
              paddingLeft='10%w';--布局内边左距
              layout_height='fill';--文本高度
              Gravity='left|center';--对齐方式
              textColor='#ffffff';--文本颜色
              text='Reading';--显示的文本
              textSize='30sp';--文本大小
            };
          };
        };
      };
    };
    {
      LinearLayout;--线性布局
      layout_marginTop='100dp';--布局外边顶距
      Orientation='vertical';--布局方向
      layout_width='fill';--布局宽度
      layout_height='fill';--布局高度
      {
        CardView;--卡片控件
        layout_width='fill';--卡片宽度
        layout_height='fill';--卡片高度
        radius='130';--卡片圆角
        CardBackgroundColor='#ffffff';--卡片背景颜色
        {
          LinearLayout;--线性布局
          Orientation='vertical';--布局方向
          layout_width='fill';--布局宽度
          layout_height='fill';--布局高度
          {
            LinearLayout;--线性布局
            Orientation='vertical';--布局方向
            layout_width='fill';--布局宽度
            layout_height='100dp';--布局高度
            {
              TextView;--文本控件
              layout_width='fill';--文本宽度
              paddingLeft='10%w';--布局内边左距
              layout_height='fill';--文本高度
              Gravity='left|center';--对齐方式
              textColor='#000000';--文本颜色
              text='All Books';--显示的文本
              textSize='30sp';--文本大小
            };
          };
          {
            ScrollView;--竖向滚动
            layout_width='90%w';--布局宽度
            layout_gravity='center';--子控件在父控件中的对齐方式
            layout_height='fill';--布局高度
            VerticalScrollBarEnabled=false;--隐藏竖向滑条
            {
              LinearLayout;--线性布局
              Orientation='vertical';--布局方向
              layout_width='fill';--布局宽度
              layout_height='fill';--布局高度
              {
                LinearLayout;--线性布局
                Orientation='horizontal';--布局方向
                layout_width='fill';--布局宽度
                layout_height='250dp';--布局高度
                {
                  LinearLayout;--线性布局
                  Orientation='vertical';--布局方向
                  layout_weight="1",
                  layout_height='fill';--布局高度
                  {
                    CardView;--卡片控件
                    layout_gravity='center';--子控件在父布局中的对齐方式
                    CardElevation='3';--卡片阴影
                    layout_width='28%w';--卡片宽度
                    layout_height='180dp';--卡片高度
                    radius='20';--卡片圆角
                    CardBackgroundColor='#30A9DE';--卡片背景颜色
                  };
                  {
                    TextView;--文本控件
                    layout_width='fill';--文本宽度
                    layout_height='fill';--文本高度
                    Gravity='center';--对齐方式
                    textColor='#6E7783';--文本颜色
                    text='Book';--显示的文本
                    textSize='20sp';--文本大小
                  };
                };
                {
                  LinearLayout;--线性布局
                  Orientation='vertical';--布局方向
                  layout_weight="1",
                  layout_height='fill';--布局高度
                  {
                    CardView;--卡片控件
                    layout_gravity='center';--子控件在父布局中的对齐方式
                    CardElevation='3';--卡片阴影
                    layout_width='28%w';--卡片宽度
                    layout_height='180dp';--卡片高度
                    radius='20';--卡片圆角
                    CardBackgroundColor='#30A9DE';--卡片背景颜色
                  };
                  {
                    TextView;--文本控件
                    layout_width='fill';--文本宽度
                    layout_height='fill';--文本高度
                    Gravity='center';--对齐方式
                    textColor='#6E7783';--文本颜色
                    text='Book';--显示的文本
                    textSize='20sp';--文本大小
                  };
                };
                {
                  LinearLayout;--线性布局
                  Orientation='vertical';--布局方向
                  layout_weight="1",
                  layout_height='fill';--布局高度
                  {
                    CardView;--卡片控件
                    layout_gravity='center';--子控件在父布局中的对齐方式
                    CardElevation='3';--卡片阴影
                    layout_width='28%w';--卡片宽度
                    layout_height='180dp';--卡片高度
                    radius='20';--卡片圆角
                    CardBackgroundColor='#30A9DE';--卡片背景颜色
                  };
                  {
                    TextView;--文本控件
                    layout_width='fill';--文本宽度
                    layout_height='fill';--文本高度
                    Gravity='center';--对齐方式
                    textColor='#6E7783';--文本颜色
                    text='Book';--显示的文本
                    textSize='20sp';--文本大小
                  };
                };
              };
              {
                LinearLayout;--线性布局
                Orientation='horizontal';--布局方向
                layout_width='fill';--布局宽度
                layout_height='250dp';--布局高度
                {
                  LinearLayout;--线性布局
                  Orientation='vertical';--布局方向
                  layout_weight="1",
                  layout_height='fill';--布局高度
                  {
                    CardView;--卡片控件
                    layout_gravity='center';--子控件在父布局中的对齐方式
                    CardElevation='3';--卡片阴影
                    layout_width='28%w';--卡片宽度
                    layout_height='180dp';--卡片高度
                    radius='20';--卡片圆角
                    CardBackgroundColor='#30A9DE';--卡片背景颜色
                  };
                  {
                    TextView;--文本控件
                    layout_width='fill';--文本宽度
                    layout_height='fill';--文本高度
                    Gravity='center';--对齐方式
                    textColor='#6E7783';--文本颜色
                    text='Book';--显示的文本
                    textSize='20sp';--文本大小
                  };
                };
                {
                  LinearLayout;--线性布局
                  Orientation='vertical';--布局方向
                  layout_weight="1",
                  layout_height='fill';--布局高度
                  {
                    CardView;--卡片控件
                    layout_gravity='center';--子控件在父布局中的对齐方式
                    CardElevation='3';--卡片阴影
                    layout_width='28%w';--卡片宽度
                    layout_height='180dp';--卡片高度
                    radius='20';--卡片圆角
                    CardBackgroundColor='#30A9DE';--卡片背景颜色
                  };
                  {
                    TextView;--文本控件
                    layout_width='fill';--文本宽度
                    layout_height='fill';--文本高度
                    Gravity='center';--对齐方式
                    textColor='#6E7783';--文本颜色
                    text='Book';--显示的文本
                    textSize='20sp';--文本大小
                  };
                };
                {
                  LinearLayout;--线性布局
                  Orientation='vertical';--布局方向
                  layout_weight="1",
                  layout_height='fill';--布局高度
                  {
                    CardView;--卡片控件
                    layout_gravity='center';--子控件在父布局中的对齐方式
                    CardElevation='3';--卡片阴影
                    layout_width='28%w';--卡片宽度
                    layout_height='180dp';--卡片高度
                    radius='20';--卡片圆角
                    CardBackgroundColor='#30A9DE';--卡片背景颜色
                  };
                  {
                    TextView;--文本控件
                    layout_width='fill';--文本宽度
                    layout_height='fill';--文本高度
                    Gravity='center';--对齐方式
                    textColor='#6E7783';--文本颜色
                    text='Book';--显示的文本
                    textSize='20sp';--文本大小
                  };
                };
              };
            };
          };
        };
      };
    };
  };
};
activity.setContentView(loadlayout(SorrowClover))