import'com.yuxuan.widget.*'

SorrowClover=
--布局请写在这里
--设置窗口视图
{
  LinearLayout;--线性布局
  Orientation='vertical';--布局方向
  layout_width='fill';--布局宽度
  layout_height='fill';--布局高度
  background='#ffffff';--布局背景颜色(或图片路径)
  {
    CardView;--卡片控件
    CardElevation='6';--卡片阴影
    layout_width='fill';--卡片宽度
    layout_height='300dp';--卡片高度
    CardBackgroundColor='#ffffff';--卡片背景颜色
    {
      WaveView;
      layout_height="150dp",
      layout_width="fill",
      id="wave",
    };
    {
      LinearLayout;--线性布局
      Orientation='horizontal';--布局方向
      layout_width='fill';--布局宽度
      layout_height='fill';--布局高度
      Gravity="bottom";
      {
        LinearLayout;--线性布局
        Orientation='vertical';--布局方向
        layout_weight='1';--权重值
        layout_height='150dp';--布局高度
        Gravity="center";
        {
          CardView;--卡片控件
          layout_gravity='center';--子控件在父布局中的对齐方式
          CardElevation='0';--卡片阴影
          layout_width='60dp';--卡片宽度
          layout_height='60dp';--卡片高度
          radius='30dp';--卡片圆角
          CardBackgroundColor='#FFDDA767';--卡片背景颜色
        };
      };
      {
        LinearLayout;--线性布局
        Orientation='vertical';--布局方向
        layout_weight='1';--权重值
        layout_height='150dp';--布局高度
        Gravity="center";
        {
          CardView;--卡片控件
          layout_gravity='center';--子控件在父布局中的对齐方式
          CardElevation='0';--卡片阴影
          layout_width='60dp';--卡片宽度
          layout_height='60dp';--卡片高度
          radius='30dp';--卡片圆角
          CardBackgroundColor='#FFDDA767';--卡片背景颜色
        };
      };
      {
        LinearLayout;--线性布局
        Orientation='vertical';--布局方向
        layout_weight='1';--权重值
        layout_height='150dp';--布局高度
        Gravity="center";
        {
          CardView;--卡片控件
          layout_gravity='center';--子控件在父布局中的对齐方式
          CardElevation='0';--卡片阴影
          layout_width='60dp';--卡片宽度
          layout_height='60dp';--卡片高度
          radius='30dp';--卡片圆角
          CardBackgroundColor='#FFDDA767';--卡片背景颜色
        };
      };
      {
        LinearLayout;--线性布局
        Orientation='vertical';--布局方向
        layout_weight='1';--权重值
        layout_height='150dp';--布局高度
        Gravity="center";
        {
          CardView;--卡片控件
          layout_gravity='center';--子控件在父布局中的对齐方式
          CardElevation='0';--卡片阴影
          layout_width='60dp';--卡片宽度
          layout_height='60dp';--卡片高度
          radius='30dp';--卡片圆角
          CardBackgroundColor='#FFDDA767';--卡片背景颜色
        };
      };
    };
  };
};
activity.setContentView(loadlayout(SorrowClover))
wave.setStartColor(0xffffffff)
wave.setCloseColor(0xFFDDA767)
wave.setWaveHeight(50)
wave.setVelocity(3)