--为了方便学习理解，我会用中文变量进行命名，但真正的项目中不推荐用中文哦
--首先创建一个布局进行动画测试
shamrock=--创建一个布局表并将其赋给变量shamrock
{
  LinearLayout;--线性布局
  Orientation='vertical';--布局方向
  layout_width='fill';--布局宽度
  layout_height='fill';--布局高度
  background='';--布局背景颜色(或者图片路径)
  Gravity='center';--设置居中
  {
    CardView;--卡片控件
    id='卡片';--绑定ID
    layout_margin='0';--卡片边距
    layout_gravity='center';--重力属性
    Elevation='0';--阴影属性
    layout_width='200';--卡片宽度
    layout_height='200';--卡片高度
    radius='20';--卡片圆角
    CardBackgroundColor='#ff7e5cf8';--卡片背景颜色
  };
};
activity.setContentView(loadlayout(shamrock))--将布局表添加至窗口

--揭露动画一定要设置延时，并在延时事件里启动
task(100,function()
--设置揭露动画，对于参数为(ID,动画圆心X轴，动画圆心Y轴,动画开始时半径,动画结束时半径)
  揭露动画 = ViewAnimationUtils.createCircularReveal(卡片,0,0,300,0)
  揭露动画.setDuration(5000)--设置动画时间
  揭露动画.start()--开始动画
end)