--[==[
ShapeDrawable是可以自定义形状񶡍rawable，
自定义圆角什么的不再是梦。
分别有五种，路径，矩形，圆角矩形，椭圆，圆
以下只演示后四种，路径在开发中基本用不上。故不做演示。
]==]
import 'android.graphics.drawable.ShapeDrawable'
import 'android.graphics.RectF'
SorrowClover=
{
  LinearLayout;--线性布局
  Orientation='vertical';--布局方向
  layout_width='fill';--布局宽度
  layout_height='fill';--布局高度
  background='#ffffff';--布局背景颜色(或图片路径)
  Gravity="center";
  {
    TextView;--文本控件
    id="rect";
    layout_width='100dp';--文本宽度
    layout_marginBottom="10dp";
    layout_height='50dp';--文本高度
    Gravity='center';--对齐方式
    textColor='#ffffff';--文本颜色
    text='矩形Shape';--显示的文本
    textSize='18sp';--文本大小
  };
  {
    TextView;--文本控件
    id="roundrect";
    layout_width='100dp';--文本宽度
    layout_marginBottom="10dp";
    layout_height='50dp';--文本高度
    Gravity='center';--对齐方式
    textColor='#ffffff';--文本颜色
    text='圆角矩形Shape';--显示的文本
    textSize='18sp';--文本大小
  };
  {
    TextView;--文本控件
    id="arc";
    layout_width='100dp';--文本宽度
    layout_marginBottom="10dp";
    layout_height='50dp';--文本高度
    Gravity='center';--对齐方式
    textColor='#ffffff';--文本颜色
    text='椭圆Shape';--显示的文本
    textSize='18sp';--文本大小
  };
  {
    TextView;--文本控件
    id="oval";
    layout_width='100dp';--文本宽度
    layout_marginBottom="10dp";
    layout_height='100dp';--文本高度
    Gravity='center';--对齐方式
    textColor='#ffffff';--文本颜色
    text='圆形Shape';--显示的文本
    textSize='18sp';--文本大小
  };
};
activity.setContentView(loadlayout(SorrowClover))
--矩形
import 'android.graphics.drawable.shapes.RectShape'
import 'android.graphics.Color'
rect_shape=ShapeDrawable(RectShape())
rect_shape.getPaint().setColor(Color.BLUE)
rect.setBackgroundDrawable(rect_shape)
--圆角矩形
import 'android.graphics.drawable.shapes.RoundRectShape'
roundrect_shape=ShapeDrawable(RoundRectShape({10,10,10,10,10,10,10,10},RectF(),{20,20,20,20,20,20,20,20}))
roundrect_shape.getPaint().setColor(Color.BLUE)
roundrect.setBackgroundDrawable(roundrect_shape)
--椭圆
import 'android.graphics.drawable.shapes.ArcShape'
arc_shape=ShapeDrawable(ArcShape(500,500))
arc_shape.getPaint().setColor(Color.BLUE)
arc.setBackgroundDrawable(arc_shape)
--圆
import 'android.graphics.drawable.shapes.OvalShape'
oval_shape=ShapeDrawable(OvalShape())
oval_shape.getPaint().setColor(Color.BLUE)
oval.setBackgroundDrawable(oval_shape)