--贝塞尔曲线
import 'com.androlua.LuaDrawable'
import 'android.graphics.Paint'
import 'android.graphics.Path'
SorrowClover=
{
  FrameLayout;--帧布局
  layout_width='fill';--布局宽度
  layout_height='fill';--布局高度
  background='#ffffff';--布局背景颜色(或图片路径)
  {
    LinearLayout;--线性布局
    Orientation='vertical';--布局方向
    layout_width='fill';--布局宽度
    layout_height='fill';--布局高度
    layout_marginBottom='300';--布局外边底距
  };
  {
    LinearLayout;--线性布局
    Orientation='horizontal';--布局方向
    layout_width='fill';--布局宽度
    layout_height='300';--布局高度
    layout_gravity='bottom';--子控件在父控件中的对齐方式
    BackgroundDrawable=LuaDrawable(function(canvas,paint,draw)
      b=draw.getBounds()
      w=b.width()
      h=b.height()
      paint.setAntiAlias(true)
      paint.setColor(0xffF17F42)
      path=Path()
      path.lineTo(b.centerX()-150,0)
      path.cubicTo(b.centerX()-75,150,b.centerX()+75,150,b.centerX()+150,0)
      path.lineTo(w,0)
      path.lineTo(w,h)
      path.lineTo(0,h)
      path.close()
      canvas.drawPath(path,paint)
    end);--布局背景颜色(或图片路径)
  };
  {
    LinearLayout;--线性布局
    layout_width='300';--布局宽度
    layout_height='300';--布局高度
    layout_gravity='bottom|center';--子控件在父控件中的对齐方式
    layout_marginBottom='200';--布局外边底距
    BackgroundDrawable=LuaDrawable(function(canvas,paint,draw)
      b=draw.getBounds()
      w=b.width()
      h=b.height()
      paint.setShadowLayer(45,0.5,0.5,0xffF17F42)
      paint.setAntiAlias(true)
      paint.setColor(0xffF17F42)
      path=Path()
      path.addCircle(b.centerX(),b.centerY(),140,Path.Direction.CCW)
      canvas.clipPath(path)
      path.moveTo(30,b.centerY())
      canvas.drawPath(path,paint)
      mypaint=Paint()
      mypaint.setColor(0xffffffff)
      mypaint.setStyle(Paint.Style.STROKE)
      mypaint.setStrokeWidth(10)
      path.lineTo(w-30,b.centerY())
      path.moveTo(b.centerX(),30)
      path.lineTo(b.centerX(),h-30)
      canvas.drawPath(path,mypaint)
    end);
  };
};
activity.setContentView(loadlayout(SorrowClover))