--[[
绝对布局即通过坐标定义组件的位置
常用属性：
layout_width	组件宽度 
layout_height	组件高度 
layout_x	设置组件的X坐标 
layout_y	设置组件的Y坐标
]]
--创建示例布局
shamrock=
{
  AbsoluteLayout;--绝对布局
  layout_width='fill';--布局宽度
  layout_height='fill';--布局高度
  background='#ffffff';--布局背景颜色(或者图片路径)
  {
    CardView;--卡片控件
    Elevation='0';--阴影属性
    layout_width='100';--卡片宽度
    layout_height='100';--卡片高度
    radius='20';--卡片圆角
    CardBackgroundColor='#ff7e5cf8';--卡片背景颜色
    layout_x='0';--定义x坐标
    layout_y='0';--定义y坐标
  };
  {
    CardView;--卡片控件
    Elevation='0';--阴影属性
    layout_width='100';--卡片宽度
    layout_height='100';--卡片高度
    radius='20';--卡片圆角
    CardBackgroundColor='#ff7e5cf8';--卡片背景颜色
    layout_x='80%w';--定义x坐标
    layout_y='0';--定义y坐标
  };
  {
    CardView;--卡片控件
    Elevation='0';--阴影属性
    layout_width='100';--卡片宽度
    layout_height='100';--卡片高度
    radius='20';--卡片圆角
    CardBackgroundColor='#ff7e5cf8';--卡片背景颜色
    layout_x='0';--定义x坐标
    layout_y='80%h';--定义y坐标
  };
  {
    CardView;--卡片控件
    Elevation='0';--阴影属性
    layout_width='100';--卡片宽度
    layout_height='100';--卡片高度
    radius='20';--卡片圆角
    CardBackgroundColor='#ff7e5cf8';--卡片背景颜色
    layout_x='80%w';--定义x坐标
    layout_y='80%h';--定义y坐标
  };
};
activity.setContentView(loadlayout(shamrock))--将布局添加至窗口