--[[
帧布局即每个组件都堆叠在前一个组件之上
常用属性：
foreground	设置改帧布局容器的前景图像
foregroundGravity	设置前景图像显示的位置
]]
--创建简单示例
shamrock=
{
  FrameLayout;--帧布局
  layout_width='fill';--布局宽度
  layout_height='fill';--布局高度
  background='#ffffff';--布局背景颜色(或者图片路径)
  {
    CardView;--卡片控件
    Elevation='0';--阴影属性
    layout_width='500';--卡片宽度
    layout_height='500';--卡片高度
    radius='0';--卡片圆角
    CardBackgroundColor='#ff7e5cf8';--卡片背景颜色
  };
  {
    CardView;--卡片控件
    Elevation='0';--阴影属性
    layout_width='400';--卡片宽度
    layout_height='400';--卡片高度
    radius='0';--卡片圆角
    CardBackgroundColor='#ff7ebef8';--卡片背景颜色
  };
  {
    CardView;--卡片控件
    Elevation='0';--阴影属性
    layout_width='300';--卡片宽度
    layout_height='300';--卡片高度
    radius='0';--卡片圆角
    CardBackgroundColor='#ff265cf8';--卡片背景颜色
  };
  {
    CardView;--卡片控件
    Elevation='0';--阴影属性
    layout_width='200';--卡片宽度
    layout_height='200';--卡片高度
    radius='0';--卡片圆角
    CardBackgroundColor='#ffce5cf8';--卡片背景颜色
  };
};
activity.setContentView(loadlayout(shamrock))--将布局添加至窗口