--[[
PageView滑动窗体即可进行滑动切换的视图，常用于初次启动欢迎界面
它没有什么特殊的方法
要说特殊也就是需要加个pages，然后在里面写布局。
需要注意的是，pages中每个视图需要有布局包裹着。
即一个布局为一个可切换窗体，
]]
SorrowClover=
{
  LinearLayout;--线性布局
  Orientation='vertical';--布局方向
  layout_width='fill';--布局宽度
  layout_height='fill';--布局高度
  {
    PageView;--滑动窗体
    pages={--生成窗体布局
      {
        LinearLayout;--线性布局
        Orientation='vertical';--布局方向
        layout_width='fill';--布局宽度
        layout_height='fill';--布局高度
        background='#ffffff';--布局背景颜色(或图片路径)
        Gravity="center",--设置居中
        {
          CardView;--卡片控件
          layout_margin='5%w';--卡片边距
          CardElevation='3';--卡片阴影
          layout_width='fill';--卡片宽度
          layout_height='fill';--卡片高度
          radius='20';--卡片圆角
          CardBackgroundColor='#A593E0';--卡片背景颜色
          {
            TextView;--文本控件
            layout_width='fill';--文本宽度
            layout_height='fill';--文本高度
            Gravity='center';--对齐方式
            textColor='#ffffff';--文本颜色
            text='ONE';--显示的文本
            textSize='50sp';--文本大小
          };
        };
      };
      {
        LinearLayout;--线性布局
        Orientation='vertical';--布局方向
        layout_width='fill';--布局宽度
        layout_height='fill';--布局高度
        background='#ffffff';--布局背景颜色(或图片路径)
        Gravity="center",--设置居中
        {
          CardView;--卡片控件
          layout_margin='5%w';--卡片边距
          CardElevation='3';--卡片阴影
          layout_width='fill';--卡片宽度
          layout_height='fill';--卡片高度
          radius='20';--卡片圆角
          CardBackgroundColor='#F68657';--卡片背景颜色
          {
            TextView;--文本控件
            layout_width='fill';--文本宽度
            layout_height='fill';--文本高度
            Gravity='center';--对齐方式
            textColor='#ffffff';--文本颜色
            text='TWO';--显示的文本
            textSize='50sp';--文本大小
          };
        };
      };
      {
        LinearLayout;--线性布局
        Orientation='vertical';--布局方向
        layout_width='fill';--布局宽度
        layout_height='fill';--布局高度
        background='#ffffff';--布局背景颜色(或图片路径)
        Gravity="center",--设置居中
        {
          CardView;--卡片控件
          layout_margin='5%w';--卡片边距
          CardElevation='3';--卡片阴影
          layout_width='fill';--卡片宽度
          layout_height='fill';--卡片高度
          radius='20';--卡片圆角
          CardBackgroundColor='#C5E99B';--卡片背景颜色
          {
            TextView;--文本控件
            layout_width='fill';--文本宽度
            layout_height='fill';--文本高度
            Gravity='center';--对齐方式
            textColor='#ffffff';--文本颜色
            text='THREE';--显示的文本
            textSize='50sp';--文本大小
          };
        };
      };
    };
  };
};
activity.setContentView(loadlayout(SorrowClover))--显示布局