import 'android.view.animation.RotateAnimation'
import 'android.view.animation.Animation'
import 'android.view.animation.AccelerateDecelerateInterpolator'
SorrowClover=
{
  LinearLayout;--线性布局
  Orientation='vertical';--布局方向
  layout_width='fill';--布局宽度
  layout_height='fill';--布局高度
  background='#ffffff';--布局背景颜色(或图片路径)
  gravity="center";
  {
    FrameLayout;--帧布局
    layout_width='100dp';--布局宽度
    layout_height='100dp';--布局高度
    {
      CardView;--卡片控件
      id="cd1";
      layout_width='fill';--卡片宽度
      layout_height='fill';--卡片高度
      Elevation='0';--阴影属性
      radius='50dp';--卡片圆角
      CardBackgroundColor='#00ffffff';--卡片背景颜色
      {
        CardView;--卡片控件
        layout_gravity='top|center';--子控件在父布局中的对齐方式
        CardElevation='0';--卡片阴影
        layout_width='10dp';--卡片宽度
        layout_height='10dp';--卡片高度
        radius='5dp';--卡片圆角
        CardBackgroundColor='#FF7268E9';--卡片背景颜色
      };
    };
    {
      CardView;--卡片控件
      id="cd2";
      layout_width='fill';--卡片宽度
      layout_height='fill';--卡片高度
      Elevation='0';--阴影属性
      radius='50dp';--卡片圆角
      CardBackgroundColor='#00ffffff';--卡片背景颜色
      {
        CardView;--卡片控件
        layout_gravity='top|center';--子控件在父布局中的对齐方式
        CardElevation='0';--卡片阴影
        layout_width='10dp';--卡片宽度
        layout_height='10dp';--卡片高度
        radius='5dp';--卡片圆角
        CardBackgroundColor='#FF7268E9';--卡片背景颜色
      };
    };
    {
      CardView;--卡片控件
      id="cd3";
      layout_width='fill';--卡片宽度
      layout_height='fill';--卡片高度
      Elevation='0';--阴影属性
      radius='50dp';--卡片圆角
      CardBackgroundColor='#00ffffff';--卡片背景颜色
      {
        CardView;--卡片控件
        layout_gravity='top|center';--子控件在父布局中的对齐方式
        CardElevation='0';--卡片阴影
        layout_width='10dp';--卡片宽度
        layout_height='10dp';--卡片高度
        radius='5dp';--卡片圆角
        CardBackgroundColor='#FF7268E9';--卡片背景颜色
      };
    };
    {
      CardView;--卡片控件
      id="cd4";
      layout_width='fill';--卡片宽度
      layout_height='fill';--卡片高度
      Elevation='0';--阴影属性
      radius='50dp';--卡片圆角
      CardBackgroundColor='#00ffffff';--卡片背景颜色
      {
        CardView;--卡片控件
        layout_gravity='top|center';--子控件在父布局中的对齐方式
        CardElevation='0';--卡片阴影
        layout_width='10dp';--卡片宽度
        layout_height='10dp';--卡片高度
        radius='5dp';--卡片圆角
        CardBackgroundColor='#FF7268E9';--卡片背景颜色
      };
    };
    {
      CardView;--卡片控件
      id="cd5";
      layout_width='fill';--卡片宽度
      layout_height='fill';--卡片高度
      Elevation='0';--阴影属性
      radius='50dp';--卡片圆角
      CardBackgroundColor='#00ffffff';--卡片背景颜色
      {
        CardView;--卡片控件
        layout_gravity='top|center';--子控件在父布局中的对齐方式
        CardElevation='0';--卡片阴影
        layout_width='10dp';--卡片宽度
        layout_height='10dp';--卡片高度
        radius='5dp';--卡片圆角
        CardBackgroundColor='#FF7268E9';--卡片背景颜色
      };
    };
    {
      CardView;--卡片控件
      id="cd6";
      layout_width='fill';--卡片宽度
      layout_height='fill';--卡片高度
      Elevation='0';--阴影属性
      radius='50dp';--卡片圆角
      CardBackgroundColor='#00ffffff';--卡片背景颜色
      {
        CardView;--卡片控件
        layout_gravity='top|center';--子控件在父布局中的对齐方式
        CardElevation='0';--卡片阴影
        layout_width='10dp';--卡片宽度
        layout_height='10dp';--卡片高度
        radius='5dp';--卡片圆角
        CardBackgroundColor='#FF7268E9';--卡片背景颜色
      };
    };
  };
};
activity.setContentView(loadlayout(SorrowClover))

function 动画(控件,时间)
  旋转动画=RotateAnimation(0, 360,
  Animation.RELATIVE_TO_SELF, 0.5,
  Animation.RELATIVE_TO_SELF, 0.5)
  旋转动画.setDuration(时间)--设置动画时间
  旋转动画.setInterpolator(AccelerateDecelerateInterpolator())
  旋转动画.setFillAfter(true)--设置动画结束后停留位置
  旋转动画.setRepeatCount(-1)--设置无限循环
  --绑定动画
  控件.startAnimation(旋转动画)
end
task(15,function()
  动画(cd1,1500)
  task(15,function()
    动画(cd2,1500)
    task(15,function()
      动画(cd3,1500)
      task(15,function()
      动画(cd4,1500)
      task(15,function()
      动画(cd5,1500)
      task(15,function()
      动画(cd6,1500)
      return true
    end)
      return true
    end)
      return true
    end)
      return true
    end)
    return true
  end)
  return true
end)