--创建一个布局，教程提供良好的可视化
dingyi=
{
  LinearLayout;--线性布局
  Orientation='vertical';--布局方向
  layout_width='fill';--布局宽度
  layout_height='fill';--布局高度
  background='#ffffff';--布局背景颜色(或者图片路径)
  gravity='center';--设置居中
  {
    CardView;--卡片控件
    layout_margin='0';--卡片边距
    layout_gravity='center';--重力属性
    Elevation='0';--阴影属性
    layout_width='150';--卡片宽度
    layout_height='150';--卡片高度
    radius='75';--卡片圆角
    CardBackgroundColor='#ff1e8ae8';--卡片背景颜色
    {
      RippleLayout,--水波纹布局
      layout_width='fill';--布局宽度
      layout_height='fill';--布局高度
      RippleColor='#ffffff';--水波纹颜色
      RippleLineColor='#ffffff';--水波纹线条颜色
      circle=true;--长按圆圈
      {
        TextView;--文本控件
        id='按钮';--绑定ID
        layout_width='fill';--文本宽度
        layout_height='fill';--文本高度
        Gravity='center';--重力属性
        textColor='#ffffff';--文本颜色
        text='点击弹窗';--显示的文本
        textSize='12sp';--文本大小
      };
    };
  };
};
activity.setContentView(loadlayout(dingyi))--将布局添加至窗口
--设置按钮点击弹出弹窗
按钮.onClick=function()
--设置弹出式窗口布局
  popbj={
    LinearLayout;--线性布局
    Orientation='vertical';--布局方向
    layout_width='80%w';--布局宽度
    layout_height='30%h';--布局高度
    background='#00ffffff';--布局背景颜色(或者图片路径)
    gravity='center';--设置居中
    {
      CardView;--卡片控件
      layout_margin='10';--卡片边距
      layout_gravity='center';--重力属性
      Elevation='10';--阴影属性
      layout_width='fill';--卡片宽度
      layout_height='fill';--卡片高度
      radius='20';--卡片圆角
      CardBackgroundColor='#ffffff';--卡片背景颜色
      {
        LinearLayout;--线性布局
        Orientation='vertical';--布局方向
        layout_width='fill';--布局宽度
        layout_height='fill';--布局高度
        background='';--布局背景颜色(或者图片路径)
        gravity='center';--设置居中
        {
          LinearLayout;--线性布局
          Orientation='vertical';--布局方向
          layout_width='55';--布局宽度
          layout_height='55';--布局高度
          background='';--布局背景颜色(或者图片路径)
          gravity='center';--设置居中
          {
            CardView;--卡片控件
            layout_margin='0';--卡片边距
            layout_gravity='center';--重力属性
            Elevation='0';--阴影属性
            layout_width='50';--卡片宽度
            layout_height='17.5';--卡片高度
            radius='0';--卡片圆角
            CardBackgroundColor='#ff1e8ae8';--卡片背景颜色
          };
          {
            CardView;--卡片控件
            layout_margin='0';--卡片边距
            layout_gravity='center';--重力属性
            Elevation='0';--阴影属性
            layout_width='25';--卡片宽度
            layout_height='8.25';--卡片高度
            radius='0';--卡片圆角
            CardBackgroundColor='#ff1e8ae8';--卡片背景颜色
          };
        };
        {
          LinearLayout;--线性布局
          Orientation='vertical';--布局方向
          layout_width='105';--布局宽度
          layout_height='105';--布局高度
          background='';--布局背景颜色(或者图片路径)
          gravity='center';--设置居中
          {
            CardView;--卡片控件
            layout_margin='0';--卡片边距
            layout_gravity='center';--重力属性
            Elevation='0';--阴影属性
            layout_width='100';--卡片宽度
            layout_height='100';--卡片高度
            radius='50';--卡片圆角
            CardBackgroundColor='#ff1e8ae8';--卡片背景颜色
            {
              CardView;--卡片控件
              layout_margin='0';--卡片边距
              layout_gravity='center';--重力属性
              Elevation='0';--阴影属性
              layout_width='90';--卡片宽度
              layout_height='90';--卡片高度
              radius='45';--卡片圆角
              CardBackgroundColor='#ffffff';--卡片背景颜色
              {
                CardView;--卡片控件
                layout_margin='0';--卡片边距
                layout_gravity='center';--重力属性
                Elevation='0';--阴影属性
                layout_width='70';--卡片宽度
                layout_height='70';--卡片高度
                radius='35';--卡片圆角
                CardBackgroundColor='#ffffff';--卡片背景颜色
                {
                  CardView;--卡片控件
                  id='指针';--绑定ID
                  layout_margin='0';--卡片边距
                  layout_gravity='top|center';--重力属性
                  Elevation='0';--阴影属性
                  layout_width='5';--卡片宽度
                  layout_height='35';--卡片高度
                  radius='1';--卡片圆角
                  CardBackgroundColor='#ff1e8ae8';--卡片背景颜色
                };
              };
            };
          };
        };
        {
          LinearLayout;--线性布局
          Orientation='vertical';--布局方向
          layout_width='fill';--布局宽度
          layout_height='100';--布局高度
          background='';--布局背景颜色(或者图片路径)
          gravity='center';--设置居中
          {
            TextView;--文本控件
            id='等待文字';--绑定ID
            layout_width='wrap';--文本宽度
            layout_height='wrap';--文本高度
            Gravity='center';--重力属性
            textColor='#ff1e8ae8';--文本颜色
            text='loading';--显示的文本
            textSize='28sp';--文本大小
          };
        };
      };
    };
  };


  pop=PopupWindow(activity)--创建PopupWindow弹出式窗口
  pop.setContentView(loadlayout(popbj))--设置布局
  pop.setWidth(activity.Width*0.8)--设置宽度
  pop.getBackground().setAlpha(0)--将pop自带的背景透明
  pop.setHeight(activity.Height*0.3)--设置高度
  pop.setFocusable(true)--设置可获得焦点
  pop.setTouchable(true)--设置可触摸
  --设置点击外部区域是否可以消失
  pop.setOutsideTouchable(false)
  --居中显示
  pop.showAtLocation(view,Gravity.CENTER,0,0)

  --设置动画的属性
  旋转动画=RotateAnimation(0,360 ,Animation.RELATIVE_TO_SELF, 1,Animation.RELATIVE_TO_SELF, 1)
  旋转动画.setDuration(800)--设置动画时间
  旋转动画.setFillAfter(true)--设置动画结束后停留位置
  旋转动画.setRepeatCount(-1)--设置无限循环
  旋转动画.setRepeatMode(Animation.RESTART)--设置循环模式
  --绑定动画
  指针.startAnimation(旋转动画)

  --设置动画属性
  透明动画=AlphaAnimation(1,0)
  透明动画.setDuration(800)--设置动画时间
  透明动画.setFillAfter(true)--设置动画后停留位置
  透明动画.setRepeatCount(-1)--设置无限循环
  透明动画.setRepeatMode(Animation.REVERSE)--设置循环模式
  --绑定动画
  等待文字.startAnimation(透明动画)

end