name: Build

on: 
  watch:
      types: [started]
  push:
    branches:
      - main    
        
      
jobs:
  deploy: #执行部署Hugo生成静态代码，默认放在gh-pages分支
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.90.1'
          extended: true #不需要extended版本就可以注释

      - name: Build github
        run: hugo
        
      - name: commit
        env:
          TZ: 'CST-8'
          emails: ${{ secrets.GITHUB_EMAIL }}
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          git config --global user.email emails
          git config --global user.name sudoskys
          datime=$(date "+%Y年%m月%d日 %H:%M")
          echo "git commit: 上传于 $datime"
          if [ -n "$(git status -s)" ];then
              git add .
              git commit -m "上传于 $datime" -a
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  


      

